'use client'
import { useState, useEffect, Suspense } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { clearMustChangePassword } from './actions'

function ChangePasswordForm() {
  const router = useRouter()
  const params = useSearchParams()
  const forced = params.get('forced') === '1'
  const returnTo = params.get('returnTo') || '/login'

  const [password, setPassword] = useState('')
  const [confirm, setConfirm] = useState('')
  const [error, setError] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [hasSession, setHasSession] = useState<boolean | null>(null)

  // Supabase's own emailed links land here with session tokens in the URL hash
  // (#access_token=...&refresh_token=...) rather than a query param, since the
  // link was generated by Supabase's server directly, not through our app's
  // PKCE-configured client. Hash fragments never reach the server, and aren't
  // always auto-picked-up, so we parse and apply them explicitly here.
  useEffect(() => {
    async function establishSession() {
      const supabase = createClient()

      const hash = window.location.hash?.startsWith('#') ? window.location.hash.slice(1) : ''
      const hashParams = new URLSearchParams(hash)
      const access_token = hashParams.get('access_token')
      const refresh_token = hashParams.get('refresh_token')

      if (access_token && refresh_token) {
        const { error: sessionError } = await supabase.auth.setSession({ access_token, refresh_token })
        // Clean the tokens out of the visible URL either way.
        window.history.replaceState(null, '', window.location.pathname + window.location.search)
        if (sessionError) {
          setHasSession(false)
          return
        }
        setHasSession(true)
        return
      }

      // No hash tokens present — check if a session already exists some other way.
      const { data } = await supabase.auth.getUser()
      setHasSession(!!data.user)
    }
    establishSession()
  }, [])

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setError('')

    if (password.length < 8) {
      setError('Password must be at least 8 characters.')
      return
    }
    if (password !== confirm) {
      setError('Passwords do not match.')
      return
    }

    setSubmitting(true)
    const supabase = createClient()
    const { data: userData, error: updateError } = await supabase.auth.updateUser({ password })
    if (updateError) {
      setSubmitting(false)
      setError(updateError.message)
      return
    }

    if (userData.user?.email) {
      await clearMustChangePassword()
    }

    setSubmitting(false)
    router.push(returnTo)
  }

  if (hasSession === false) {
    return (
      <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'var(--bg)' }}>
        <div className="card" style={{ width: '100%', maxWidth: 380 }}>
          <div className="panel-body">
            <p style={{ color: 'var(--danger)', marginBottom: 12 }}>This link has expired or was already used.</p>
            <a href="/login" className="btn btn-primary" style={{ textDecoration: 'none' }}>Back to login</a>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'var(--bg)' }}>
      <div className="card" style={{ width: '100%', maxWidth: 380 }}>
        <div className="panel-head"><h2>{forced ? 'Set your password' : 'Change password'}</h2></div>
        <form onSubmit={handleSubmit}>
          <div className="panel-body">
            <p className="hint" style={{ marginBottom: 14 }}>
              {forced
                ? "You're using a temporary password — set your own before continuing."
                : 'Choose a new password for your account.'}
            </p>
            <div className="form-row">
              <label>New password</label>
              <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required minLength={8} autoFocus disabled={hasSession === null} />
            </div>
            <div className="form-row">
              <label>Confirm password</label>
              <input type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} required minLength={8} disabled={hasSession === null} />
            </div>
            {error && <p style={{ color: 'var(--danger)', fontSize: 12.5, marginBottom: 10 }}>{error}</p>}
            <button type="submit" className="btn btn-primary" disabled={submitting || hasSession === null} style={{ width: '100%' }}>
              {hasSession === null ? 'Checking…' : submitting ? 'Saving…' : 'Set password & continue'}
            </button>
            {!forced && (
              <button
                type="button"
                onClick={() => router.push(returnTo)}
                className="btn btn-ghost"
                style={{ width: '100%', marginTop: 8 }}
              >
                Cancel
              </button>
            )}
          </div>
        </form>
      </div>
    </div>
  )
}

export default function ChangePasswordPage() {
  return (
    <Suspense fallback={null}>
      <ChangePasswordForm />
    </Suspense>
  )
}