'use server'

import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { revalidatePath } from 'next/cache'
import { generateTempPassword } from '@/lib/password'

const ROLE_HOME: Record<string, string> = { Admin: '/admin', Manager: '/manager', Member: '/member' }

/** Sends the setup link via Supabase's own built-in mailer — works for any real
 *  email immediately, no domain/DNS setup needed. The link this produces carries
 *  session tokens in the URL hash (not a PKCE code), since it's generated by
 *  Supabase's server directly rather than through our PKCE-locked browser client —
 *  the change-password page picks this up via a manual hash-fragment check. */
async function sendSetupLink(email: string, role: string) {
  const supabase = await createClient()
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'
  const home = ROLE_HOME[role] ?? '/login'

  const { error } = await supabase.auth.resetPasswordForEmail(email, {
    redirectTo: `${siteUrl}/auth/change-password?forced=1&returnTo=${encodeURIComponent(home)}`,
  })

  if (error) {
    console.error('Failed to send setup email:', error)
    return { success: false, error: error.message }
  }
  return { success: true }
}

export async function createCampaignAction(formData: FormData) {
  const supabase = await createClient()

  const clientId = formData.get('clientId') as string
  const projectName = formData.get('projectName') as string
  const startDate = formData.get('startDate') as string
  const managerName = formData.get('managerName') as string
  const deliverablesJson = formData.get('deliverables') as string
  const deliverables = JSON.parse(deliverablesJson) as { name: string; type: string }[]

  const { data: clientRow, error: clientError } = await supabase
    .from('clients')
    .select('name')
    .eq('id', Number(clientId))
    .single()

  if (clientError || !clientRow) {
    console.error('createCampaignAction client lookup error:', clientError)
    throw new Error('Could not find the selected client.')
  }

  const { data: newProject, error: projectError } = await supabase
    .from('projects')
    .insert({
      project_name: projectName,
      client_id: Number(clientId),
      client_name: clientRow.name,
      content_format: deliverables[0]?.type || 'Mixed',
      start_date: startDate,
      end_date: null,
      status: 'New',
      manager: managerName ? [managerName] : [],
      assignee: [],
      priority: 'Medium',
      time_scale: null,
      completion_percent: 0,
      deliverables: deliverables.length,
    })
    .select()
    .single()

  if (projectError || !newProject) {
    console.error('createCampaignAction error:', projectError)
    throw new Error(projectError?.message || 'Failed to create project.')
  }

  const { data: typeMap } = await supabase.from('sequence_deliverable_types').select('*')
  const { data: allSeqStages } = await supabase.from('sequence_stages').select('*').order('stage_order')

  for (const [i, deliv] of deliverables.entries()) {
    const matchedType = typeMap?.find(t => t.type_name === deliv.type)
    const sequenceId = matchedType?.sequence_id ?? null

    const { data: newDeliverable } = await supabase
      .from('deliverables')
      .insert({
        project_id: newProject.id,
        name: deliv.name || `Deliverable ${i + 1}`,
        content_format: deliv.type,
        sequence_id: sequenceId,
      })
      .select()
      .single()

    if (newDeliverable && sequenceId) {
      const stagesForSeq = (allSeqStages ?? []).filter(s => s.sequence_id === sequenceId)

      const stageRows = stagesForSeq.map((s, idx) => ({
        deliverable_id: newDeliverable.id,
        stage_name: s.stage_name,
        department: s.department,
        status: idx === 0 ? 'in_progress' : 'pending',
        stage_order: idx,
      }))

      if (stageRows.length > 0) {
        await supabase.from('deliverable_stages').insert(stageRows)
      }
    }
  }

  revalidatePath('/admin/clients')
}

export async function createClientAction(formData: FormData) {
  const supabase = await createClient()

  const name = formData.get('name') as string
  const email = formData.get('email') as string
  const accountManager = formData.get('accountManager') as string

  const { error } = await supabase.from('clients').insert({
    name,
    email,
    account_manager: accountManager,
    status: 'Active',
  })

  if (error) {
    console.error('createClientAction error:', error)
    throw new Error(error.message)
  }

  revalidatePath('/admin/clients')
}

export async function addHolidayAction(formData: FormData) {
  const supabase = await createClient()
  const name = formData.get('name') as string
  const date = formData.get('date') as string

  const { error } = await supabase.from('holidays').insert({ name, date })
  if (error) {
    console.error('addHolidayAction error:', error)
    throw new Error(error.message)
  }
  revalidatePath('/admin/settings')
}

export async function removeHolidayAction(id: number) {
  const supabase = await createClient()
  const { error } = await supabase.from('holidays').delete().eq('id', id)
  if (error) {
    console.error('removeHolidayAction error:', error)
    throw new Error(error.message)
  }
  revalidatePath('/admin/settings')
}

export async function updateOrgSettingsAction(formData: FormData) {
  const supabase = await createClient()
  const timezone = formData.get('timezone') as string
  const dayStarts = formData.get('dayStarts') as string
  const dayEnds = formData.get('dayEnds') as string

  const { data: existing } = await supabase.from('org_settings').select('id').limit(1).single()

  if (existing) {
    const { error } = await supabase
      .from('org_settings')
      .update({ timezone, day_starts: dayStarts, day_ends: dayEnds, updated_at: new Date().toISOString() })
      .eq('id', existing.id)
    if (error) {
      console.error('updateOrgSettingsAction error:', error)
      throw new Error(error.message)
    }
  }

  revalidatePath('/admin/settings')
}

export async function resendPasswordEmailAction(email: string, role: string) {
  const result = await sendSetupLink(email, role)
  if (!result.success) {
    throw new Error(result.error)
  }
  revalidatePath('/admin/users')
}

export async function inviteUserAction(formData: FormData) {
  const supabase = await createClient()
  const admin = createAdminClient()

  const name = formData.get('name') as string
  const email = formData.get('email') as string
  const department = formData.get('department') as string
  const role = formData.get('role') as string

  // Create the real Supabase Auth account first — if this fails (e.g. email
  // already exists), we haven't created a duplicate managers row yet.
  // The generated password makes the account instantly usable; nobody ever
  // sees this value — they set their own via the email link sent below.
  const tempPassword = generateTempPassword()
  const { error: createError } = await admin.auth.admin.createUser({
    email,
    password: tempPassword,
    email_confirm: true,
    user_metadata: { name, role, department },
  })

  if (createError) {
    console.error('Failed to create auth account:', createError)
    throw new Error(createError.message)
  }

  const { error } = await supabase.from('managers').insert({ name, email, department, role, must_change_password: true })
  if (error) {
    console.error('inviteUserAction error:', error)
    throw new Error(error.message)
  }

  // Sends the setup link via Supabase's own mailer — see sendSetupLink's comment above.
  const emailResult = await sendSetupLink(email, role)

  if (!emailResult.success) {
    console.error('Failed to send account-setup email:', emailResult.error)
  }

  revalidatePath('/admin/users')
}

export async function createSequenceAction(formData: FormData) {
  const supabase = await createClient()
  const name = formData.get('name') as string
  const description = formData.get('description') as string
  const isDefault = formData.get('isDefault') === 'on'
  const stagesJson = formData.get('stages') as string
  const stages = JSON.parse(stagesJson) as { name: string; department: string }[]
  const typesJson = formData.get('deliverableTypes') as string
  const deliverableTypes = typesJson ? (JSON.parse(typesJson) as string[]) : []

  if (isDefault) {
    await supabase.from('sequences').update({ is_default: false }).neq('id', 0)
  }

  const { data: newSeq, error } = await supabase
    .from('sequences')
    .insert({ name, description, is_default: isDefault })
    .select()
    .single()

  if (error) {
    console.error('createSequenceAction error:', error)
    throw new Error(error.message)
  }

  const stageRows = stages.map((stage, i) => ({
    sequence_id: newSeq.id,
    stage_name: stage.name,
    department: stage.department,
    stage_order: i + 1,
  }))

  await supabase.from('sequence_stages').insert(stageRows)

  if (deliverableTypes.length > 0) {
    const typeRows = deliverableTypes.map(type_name => ({
      sequence_id: newSeq.id,
      type_name,
    }))
    const { error: typeError } = await supabase.from('sequence_deliverable_types').insert(typeRows)
    if (typeError) {
      // Most likely a duplicate type_name already claimed by another sequence (UNIQUE constraint).
      console.error('createSequenceAction deliverable types error:', typeError)
    }
  }

  revalidatePath('/admin/sequences', 'layout')
}

export async function clientApproveStageAction(deliverableStageId: number, feedback: string) {
  const supabase = await createClient()
  const { error } = await supabase
    .from('deliverable_stages')
    .update({ status: 'complete', note: feedback || null })
    .eq('id', deliverableStageId)
  if (error) throw new Error(error.message)
  revalidatePath('/client')
}

export async function clientRequestChangesAction(deliverableStageId: number, feedback: string) {
  const supabase = await createClient()
  const { data: stage } = await supabase.from('deliverable_stages').select('revision_count').eq('id', deliverableStageId).single()
  const { error } = await supabase
    .from('deliverable_stages')
    .update({ status: 'feedback', note: feedback, revision_count: (stage?.revision_count ?? 0) + 1 })
    .eq('id', deliverableStageId)
  if (error) throw new Error(error.message)
  revalidatePath('/client')
}
export async function getPendingRegistrations() {
  const supabase = await createClient()
  const admin = createAdminClient()

  const { data: authUsers, error } = await admin.auth.admin.listUsers({ perPage: 200 })
  if (error) {
    console.error('getPendingRegistrations error:', error)
    return []
  }

  const { data: existingManagers } = await supabase.from('managers').select('email')
  const knownEmails = new Set((existingManagers ?? []).map(m => m.email))

  return authUsers.users
    .filter(u => u.email && !knownEmails.has(u.email))
    .map(u => ({
      id: u.id,
      email: u.email as string,
      name: (u.user_metadata?.name as string) || u.email!.split('@')[0],
      createdAt: u.created_at,
    }))
}

export async function approveUserAction(formData: FormData) {
  const supabase = await createClient()

  const name = formData.get('name') as string
  const email = formData.get('email') as string
  const role = formData.get('role') as string
  const department = formData.get('department') as string

  // They already set their own password during registration — no forced change needed.
  const { error } = await supabase.from('managers').insert({ name, email, role, department, must_change_password: false })
  if (error) {
    console.error('approveUserAction error:', error)
    throw new Error(error.message)
  }

  revalidatePath('/admin/users')
}

export async function updateSequenceAction(formData: FormData) {
  const supabase = await createClient()
  const id = Number(formData.get('id'))
  const name = formData.get('name') as string
  const description = formData.get('description') as string
  const isDefault = formData.get('isDefault') === 'on'
  const stages = JSON.parse(formData.get('stages') as string) as { name: string; department: string }[]
  const typesJson = formData.get('deliverableTypes') as string
  const deliverableTypes = typesJson ? (JSON.parse(typesJson) as string[]) : []

  if (isDefault) {
    await supabase.from('sequences').update({ is_default: false }).neq('id', id)
  }

  const { error } = await supabase.from('sequences').update({ name, description, is_default: isDefault }).eq('id', id)
  if (error) {
    console.error('updateSequenceAction error:', error)
    throw new Error(error.message)
  }

  // Replace stages and deliverable types wholesale.
  const { error: deleteStagesError } = await supabase.from('sequence_stages').delete().eq('sequence_id', id)
  if (deleteStagesError) {
    console.error('Failed to clear old stages:', deleteStagesError)
    throw new Error(`Could not update stages: ${deleteStagesError.message}`)
  }
  const stageRows = stages.map((stage, i) => ({ sequence_id: id, stage_name: stage.name, department: stage.department, stage_order: i + 1 }))
  if (stageRows.length > 0) {
    const { error: insertStagesError } = await supabase.from('sequence_stages').insert(stageRows)
    if (insertStagesError) {
      console.error('Failed to insert new stages:', insertStagesError)
      throw new Error(`Could not save stages: ${insertStagesError.message}`)
    }
  }

  const { error: deleteTypesError } = await supabase.from('sequence_deliverable_types').delete().eq('sequence_id', id)
  if (deleteTypesError) {
    console.error('Failed to clear old deliverable types:', deleteTypesError)
    throw new Error(`Could not update deliverable types: ${deleteTypesError.message}`)
  }
  if (deliverableTypes.length > 0) {
    const { error: insertTypesError } = await supabase.from('sequence_deliverable_types').insert(deliverableTypes.map(type_name => ({ sequence_id: id, type_name })))
    if (insertTypesError) {
      console.error('Failed to insert new deliverable types:', insertTypesError)
      throw new Error(`Could not save deliverable types: ${insertTypesError.message}`)
    }
  }

  revalidatePath('/admin/sequences', 'layout')
  revalidatePath(`/admin/sequences/${id}`)
}

export async function deleteSequenceAction(id: number) {
  const supabase = await createClient()

  const { count } = await supabase.from('deliverables').select('id', { count: 'exact', head: true }).eq('sequence_id', id)
  if (count && count > 0) {
    throw new Error(`Can't delete — ${count} existing deliverable${count > 1 ? 's' : ''} still use this sequence.`)
  }

  await supabase.from('sequence_stages').delete().eq('sequence_id', id)
  await supabase.from('sequence_deliverable_types').delete().eq('sequence_id', id)
  const { error } = await supabase.from('sequences').delete().eq('id', id)
  if (error) {
    console.error('deleteSequenceAction error:', error)
    throw new Error(error.message)
  }

  revalidatePath('/admin/sequences', 'layout')
}

export async function updateCampaignAction(formData: FormData) {
  const supabase = await createClient()
  const id = Number(formData.get('id'))
  const projectName = formData.get('projectName') as string
  const managerName = formData.get('managerName') as string
  const priority = formData.get('priority') as string
  const status = formData.get('status') as string
  const startDate = formData.get('startDate') as string

  const { error } = await supabase
    .from('projects')
    .update({
      project_name: projectName,
      manager: managerName ? [managerName] : [],
      priority,
      status,
      start_date: startDate,
    })
    .eq('id', id)

  if (error) {
    console.error('updateCampaignAction error:', error)
    throw new Error(error.message)
  }

  revalidatePath('/admin/clients')
}

export async function deleteCampaignAction(id: number) {
  const supabase = await createClient()

  const { data: deliverableRows } = await supabase.from('deliverables').select('id').eq('project_id', id)
  const deliverableIds = (deliverableRows ?? []).map(d => d.id)

  if (deliverableIds.length > 0) {
    await supabase.from('deliverable_stages').delete().in('deliverable_id', deliverableIds)
    await supabase.from('deliverables').delete().eq('project_id', id)
  }

  const { error } = await supabase.from('projects').delete().eq('id', id)
  if (error) {
    console.error('deleteCampaignAction error:', error)
    throw new Error(error.message)
  }

  revalidatePath('/admin/clients')
}