[program:nextjs]
command=/usr/bin/npx next start -H 0.0.0.0 -p 3000
directory=/app
autostart=true
autorestart=true
environment=NODE_ENV="production",HOST="0.0.0.0",PORT="3000"
stderr_logfile=/var/log/supervisor/nextjs.err.log
stdout_logfile=/var/log/supervisor/nextjs.out.log
stopsignal=TERM
stopwaitsecs=30
stopasgroup=true
killasgroup=true
